sudo: false
language: node_js
node_js: stable
before_script:
- git config --global user.name 'genthaler'
- git config --global user.email 'genthaler@users.noreply.github.com'
- git remote set-url origin "https://${GH_TOKEN}@github.com/genthaler/elm-enum.git"
- npm install -g elm@latest
- elm --version
- npm install -g elm-test@beta
- elm-test --version

script:
- cd example && elm-test

env:
  global:
  - GH_REF: github.com/genthaler/elm-enum.git
  - GITHUB_REPO: genthaler/elm-enum
