sudo: false
language: node_js
node_js: stable
before_script:
- git config --global user.name 'genthaler'
- git config --global user.email 'genthaler@users.noreply.github.com'
- git remote set-url origin "https://${GH_TOKEN}@github.com/genthaler/elm-enum.git"
- npm install elm@latest
- elm --version
- npm install elm-test@latest
- elm-test --version

script:
- elm-package install --yes
- elm-make --yes
- elm-test

cache:
  directories:
  - elm-stuff/packages
env:
  global:
  - GH_REF: github.com/genthaler/elm-enum.git
  - GITHUB_REPO: genthaler/elm-enum
